### ISSUE TITLE
rename the repository

### ISSUE THREAD

**Issue by rubo77** [viisauksena/gluon-ssid-changer#6]
since this package is completely another approach as the gluon-ssid-changer by ffac, you should rename the whole repository here in settings, for example into

```
gluon-offline-ssid
```

**Comment by viisauksena** [comment]
the point of relevance is, that ffac and i try to make packages to evaluate if these in some kind could go to the main branch of gluon itself. There are not there, so you have manually adopt these in the modules file. That is inconvinient if you have ffac and mine version in modules file and try to add gluon-ssid-changer to site.mk, which hopefully leads to an error. (since its not predictable, and gluon knows 2 packages by this name than)
I see your point, but as these are in the wild used scripts and "renaming" means mainly delete and make new. i prefer to let this package evolve as it is, including freiburg specific stuff. And if this come into gluon itself - then i am more than willed to participate for progress. But thats also the point where this old naming scheme will brake, if there are than a official_gluon_ssid_changer and a modules_based_ssid_changer. (principle occurs toother packages too) ... i wrote quite some of these, and all have a hard way coming mainstream - seem not to happen.
in future i will name packages like fffr-whatever , and would do a rewrite for gluon if there is interest.
